name: mypos_emp_management
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.2
  http: ^0.13.4
  google_fonts: ^2.3.2
  image_picker: ^0.8.5+3
  jiffy: ^5.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  octo_image: ^1.0.1
  image_cropper: ^2.0.2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
